src/build/Commands/BuildCommand.cs
src/build/Commands/CleanCommand.cs
src/build/Commands/FetchCommand.cs
src/build/Program.cs

Note that the default log prefix is the name of the entry assembly, which is already "ElastiBuild".

remove redundant code from src/build

---

.buildkite/pipeline.yml
.buildkite/scripts/build.ps1

This pipeline replaced the existing jenkins one defined here. 
It doesn't do much, but is equivalent to the one in Jenkins. 
The next step is to grab the script from the RM and add it here in a follow up PR and upload artefacts.
Rel https://github.com/elastic/release-eng/issues/529

Create a buildkite pipeline to replace Jenkins

---

.buildkite/pipeline.yml
.buildkite/scripts/build.ps1
.buildkite/scripts/dra-publish.sh

Resolves 8.9 snapshot break
8.9 dra produce 
The last invocation should resolve the beat dependency manifest https://buildkite.com/elastic/elastic-stack-installers/builds/304
After Merge needs to be backported to `8.8` & `8.7`

Snapshot-bugfix

---

.buildkite/scripts/build.ps1
Directory.Build.props

Relates to [#715](https://github.com/elastic/release-eng/issues/715)
Bump stack installers version to 8.8.2

bump to 8.8.2

---

catalog-info.yaml

The branch value for a scheduled pipeline must be a string.
```
:no_entry:  Validation result:
:no_entry:	7.17 is not of type 'string'
:no_entry:
:no_entry:	Failed validating 'type' in schema['properties']['spec']['properties']['schedules']['patternProperties']['.*']['properties']['branch']:
:no_entry:	    {'type': 'string'}
:no_entry:
:no_entry:	On instance['spec']['schedules']['Weekly main']['branch']:
:no_entry:	    7.17
```

branch value for schedule must be string

---

.buildkite/scripts/check_beats.sh
catalog-info.yaml

This PR is the first part, to add an empty pipeline that can then be used to check for beats and trigger if newer is available.

Add a new pipeline to trigger a build if newer beats is available

---

catalog-info.yaml

Remove 8.8 DRA builds as 8.9 is released on 25-07-2023
Relates to[ #589](https://elasticco.atlassian.net/browse/REL-589)
https://github.com/elastic/release-eng/issues/733

Remove 8.8 dra builds

---

.buildkite/scripts/build.ps1
catalog-info.yaml

Removes the direct triggers for non main builds, adds the beats trigger check for 8.10 and bumps main to 8.11

Bump main to 8.11 add 8.10 to schedule

---

.github/CODEONWERS
CODEOWNERS
catalog-info.yaml

This PR transfer the repository ownership from release-eng team to
the ingest-fp team.
The release-eng team will keep admin permissions for a while to finalize
the transfer and move the artifacts signing process outside of the
snapshot/staging pipeline.
cc @pazone  @roaksoax @pierrehilbert @alsayasneh

Transfer repo and pipeline ownership to ingest-fp

---

.buildkite/pipeline.yml

This PR update the Buildkite pipeline notifs to ping Ingest team Slack channel instead of Release Eng.

Notify Ingest team when pipeline fails

---

.buildkite/pipeline.yml
CODEOWNERS
catalog-info.yaml

Backport https://github.com/elastic/elastic-stack-installers/pull/184 and https://github.com/elastic/elastic-stack-installers/pull/186 to 7.17 branch

Transfer repo and pipeline ownership to ingest-fp (7.17)

---

.buildkite/pipeline.yml
.github/CODEONWERS
CODEOWNERS
catalog-info.yaml

Backport https://github.com/elastic/elastic-stack-installers/pull/184 and https://github.com/elastic/elastic-stack-installers/pull/186 to 8.10 branch

Transfer repo and pipeline ownership to ingest-fp (8.10)

---

README.md

This PR add the procedure to bump the elastic-stack-installer version after a patch or minor release.
⚠️ to backport to 8.11, 8.10, and 7.17 branches

Add bumping doc

---

.buildkite/scripts/dra-publish.sh

This commit fixes a bug introduced in PR #212 which missed the switch from WORKFLOW -> DRA_WORKFLOW from the publish step, resulting in failures[^1].
[^1]: https://buildkite.com/elastic/elastic-stack-installers/builds/3641#018d5b0b-5ae5-404c-b79f-211468f45413/51-52

Fix dra publish step

---

.buildkite/scripts/dra-publish.sh

This commit fixes the downloaded artifacts path to the expected path by the release manager image (`bin/out`).
The original path was changed in #212 and the previous step because path lengths exceeded a limit imposed by the msi builder.
Example failure: https://buildkite.com/elastic/elastic-stack-installers/builds/3653#018d5d99-9403-41b5-9023-613016deb033/51-54

Fix artifacts path for dra publish

---

.buildkite/scripts/build.ps1

We got a random failure(^1) in a sequence of runs where it didn't fail before, so muting it for now, as it shouldn't be blocking the unified release. Tests will be reenabled as part of
https://github.com/elastic/elastic-stack-installers/pull/225/files
[^1]: https://buildkite.com/elastic/elastic-stack-installers/builds/3671#018d5f93-affb-4019-a534-b53fcf8fe1e9/3813-5280
cc @strawgate

Disable msi agent tests

---

.buildkite/pipeline.yml
.buildkite/scripts/build.ps1
.buildkite/scripts/test.ps1
catalog-info.yaml
src/agent-qa/helpers.ps1

PR #212 made some changes on `main` that require the presence of `MANIFEST_URL`. However, the pipeline is still configured to run the same script when a PR (from an upstream branch) is raised and it currently fails.
This commit skips tests when triggered from another pipeline (unified release), and allows running tests when triggered by PR creation by picking up a suitable `MANIFEST_URL`.

Selectively skip and fix tests after PR#212

---

docs/beats.md
docs/elastibuild.md
src/installer/BeatPackageCompiler/Properties/Resources.Designer.cs
src/installer/BeatPackageCompiler/Properties/Resources.resx

The same as https://github.com/elastic/elastic-stack-installers/pull/234 but the branch is in this repository instead of my fork so CI will actually run.
Store configuration, runtime, and log data in ProgramFiles.
This is a follow up from https://github.com/elastic/elastic-stack-installers/pull/209

Do not use program data in Beats MSI installers

---

.buildkite/pipeline.yml

This commit tightens the pipeline conditionals to ensure the snapshot job doesn't run when the unified release triggers staging.
The allowed workflows are:
i) Allow PRs to run the pipeline, if targeting main or release branches
ii) Runs the pipeline when triggered by the unified release SNAPSHOT, if targeting main or release branches
We rely on the conditional of the dra publish script to just run in dry-run mode, if run via PR; can't test it yet due to above issue with 8.14.0-SNAPSHOT missing. If we hit unforeseen issues, we may add a conditional in a follow up to only let it run from unified-release triggers.
Only runs the pipeline when triggered by the unified release STAGING, if targeting release branches. Won't run via PRs.
Relates …

Don't run snapshot DRA when triggered by staging

---

.buildkite/scripts/build.ps1

This commit fixes a bug with regexp matching
from the build script, when checking if running
the PR is eligible against release branches >=8.
Relates #248

Allow PRs to run against non main branches

---

.buildkite/pipeline.yml

This commit tightens the pipeline conditionals to ensure the snapshot job doesn't run when the unified release triggers staging.
Relates https://github.com/elastic/elastic-stack-installers/pull/244
Backport of #248

Don't run snapshot DRA when triggered by staging (#248)

---

.buildkite/scripts/build.ps1

This commit fixes a bug with regexp matching from the build script, when checking if running the PR is eligible against release branches >=8.
Backport of #250

Allow PRs to run against non main branches (#250)

---

.buildkite/pipeline.yml

Even though the dra publish script attempts to
run the release manager in dry-run mode, there's
no value allowing the step to run via PRs, because it fails since it's working with an unrecognized
branch e.g. `The specified project directory '/release/project-configs/test-prs' does not exist.`
Example failure: https://buildkite.com/elastic/elastic-stack-installers/builds/3910#018dcc46-d6c9-4845-bf0f-be61a7dd307e/73-101
This commit skips the DRA publish step when the snapshot pipeline gets triggered by PRs.

Don't run snapshot DRA publish with PRs

---

.buildkite/pipeline.yml

Even though the dra publish script attempts to
run the release manager in dry-run mode, there's
no value allowing the step to run via PRs, because it fails since it's working with an unrecognized
branch e.g. `The specified project directory '/release/project-configs/test-prs' does not exist.`
Example failure: https://buildkite.com/elastic/elastic-stack-installers/builds/3910#018dcc46-d6c9-4845-bf0f-be61a7dd307e/73-101
This commit skips the DRA publish step when the snapshot pipeline gets triggered by PRs.

Don't run snapshot DRA publish with PRs (#255)

---

.buildkite/pipeline.yml

Images have been renamed a while ago, this commit updates the Windows image names used by CI.

Use actually maintained CI VM images

---

.buildkite/pipeline.yml

Images have been renamed a while ago, this commit updates the Windows image names used by CI.

Use actually maintained CI VM images (#276)

---

.buildkite/pipeline.yml
.buildkite/scripts/dra-publish.sh

This commit adds support for VERSION_QUALIFIER to DRA.
This commit was cherry picked from b0e45db2a4ddbdebf5e0f9c4974ad8ecf12d9ea7

Backport #302 to 8.x: Support prereleases (#302)

---

.buildkite/pipeline.yml
.buildkite/scripts/dra-publish.sh

This commit adds support for VERSION_QUALIFIER to DRA.
This commit has been cherry-picked from b0e45db2a4ddbdebf5e0f9c4974ad8ecf12d9ea7

Backport #302 to 8.17: Support prereleases (#302)

---

.buildkite/pipeline.yml
.buildkite/scripts/version_qualifier.ps1
.buildkite/scripts/version_qualifier.sh

To avoid manual invocations specifying the version qualifier for prereleases in this commit we leverage a centralized version of truth for the version qualifier.

Use centralized version qualifier

---

.buildkite/pipeline.yml
.buildkite/scripts/version_qualifier.ps1
.buildkite/scripts/version_qualifier.sh

This is a forward port of commit be245933ec6d144b22fb1726cdb18557519c1df0 to main

Forward port #307 to main: Use centralized version qualifier (#307)

---

.buildkite/pipeline.yml
.buildkite/scripts/version_qualifier.ps1
.buildkite/scripts/version_qualifier.sh

This is a backport of commit be245933ec6d144b22fb1726cdb18557519c1df0 to 8.x

Backport #307 to 8.x: Use centralized version qualifier (#307)

---

.buildkite/pipeline.yml
.buildkite/scripts/version_qualifier.ps1
.buildkite/scripts/version_qualifier.sh

This is a backport of commit be245933ec6d144b22fb1726cdb18557519c1df0 to 8.18

Backport 307 to 8.18: Use centralized version qualifier (#307)

---

.buildkite/pipeline.yml
.buildkite/scripts/version_qualifier.ps1
.buildkite/scripts/version_qualifier.sh

This is a backport of commit https://github.com/elastic/elastic-stack-installers/commit/be245933ec6d144b22fb1726cdb18557519c1df0 to 8.17

Backport 307 to 8.17: Use centralized version qualifier (#307)

---

.buildkite/pipeline.yml
.buildkite/scripts/version_qualifier.ps1
.buildkite/scripts/version_qualifier.sh

This is a backport of commit be24593 to 8.16

Backport 307 to 8.16: Use centralized version qualifier (#307)

---

.buildkite/pipeline.yml

Example triggered run https://buildkite.com/elastic/elastic-stack-installers/builds/9222#0194d63b-e9a4-4a53-bc19-e049e610e21b

Provide a way to manually run staging builds

---

.buildkite/pipeline.yml

This commit is cherry picked from 811b64ea12be5ee5a1cd3f40f46e2ce78c92ad82

Backport #313 to 8.x: Fix sourcing of version_qualifier.ps1 in CI (#313)

---

.buildkite/pipeline.yml

This commit is cherry picked from https://github.com/elastic/elastic-stack-installers/commit/811b64ea12be5ee5a1cd3f40f46e2ce78c92ad82

Backport #313 to 8.18: Fix sourcing of version_qualifier.ps1 in CI (#313)

---

.buildkite/pipeline.yml

This commit is cherry-picked from 6fbe771c593b382e9f01529d127ec488460e767a

Forward port #314 to `main`: Provide a way to manually run staging builds (#314)

---

.buildkite/pipeline.yml

This commit is cherry-picked from 6fbe771c593b382e9f01529d127ec488460e767a

Backport #314 to 8.x: Provide a way to manually run staging builds (#314)

---

.buildkite/pipeline.yml

This commit is cherry-picked from 6fbe771c593b382e9f01529d127ec488460e767a

Backport #314 to 8.17: Provide a way to manually run staging builds (#314)

---

.buildkite/pipeline.yml

This commit is cherry-picked from 6fbe771c593b382e9f01529d127ec488460e767a

Backport #314 to 8.16: Provide a way to manually run staging builds (#314)
