Directory.Build.props

7.9.2 is released, bump to 7.9.3.

Version bump: 7.9.3

---

Directory.Build.props

[release] Bump version to 7.13.1

---

Directory.Build.props

7.16.0 is released, bump to 7.16.1

Version bump v7.16.1

---

Directory.Build.props

Version bump v7.16.3

---

Directory.Build.props

8.0.2 version bump

---

Directory.Build.props

Bump to 8.1.4

---

Directory.Build.props

bump to 8.5.4

---

Directory.Build.props

bump stack installers version to 8.8.0

bump version to 8.8.0

---

.buildkite/scripts/dra-publish.sh

fix dra branch

---

.buildkite/pipeline.yml
.buildkite/scripts/build.ps1
.buildkite/scripts/dra-publish.sh
Directory.Build.props

fixes dra bug with version branches.

Dra-bug-fix (#122

---

.buildkite/pipeline.yml

change staging phase filter (#123

---

.github/CODEONWERS

add release-eng as code owners

add codeowners (#130

---

.buildkite/scripts/build.ps1
Directory.Build.props

bump main version to 8.9

---

catalog-info.yaml

Follow-up of https://github.com/elastic/elastic-stack-installers/pull/146

Fix catalog indentation

---

.buildkite/scripts/build.ps1
Directory.Build.props

Relates https://github.com/elastic/release-eng/issues/690
Bump stack installers version to 8.8.1

Bump stack version

---

catalog-info.yaml

Removing 8.7 schedule as we won't release anymore

remove 8.7 schedule

---

catalog-info.yaml

Add a scheduled 7.17 weekly build.

Build 7.17 weekly

---

.buildkite/scripts/build.ps1
Directory.Build.props
catalog-info.yaml

Relates to https://github.com/elastic/release-eng/issues/733

Bump to 8.10 and update 8.9 schedule

---

.buildkite/pipeline.yml

Backport https://github.com/elastic/elastic-stack-installers/pull/154

Fix Build Slack notifs for 8.9 branch

---

.buildkite/pipeline.yml

Relates to https://elasticco.atlassian.net/browse/REL-370

Do not trigger staging builds by default

---

.buildkite/scripts/build.ps1
Directory.Build.props

To merge when all projects are bumped in https://elastic.slack.com/archives/C0JFN9HJL/p1688025361508959
Related to https://github.com/elastic/release-eng/issues/728

[release] bump stack-installer to 8.8.3

---

.buildkite/scripts/build.ps1

Beats is now available in DRA similar to 8.x

Consume beats from DRA simmilar to 8.x

---

.buildkite/scripts/check_beats.sh
.buildkite/trigger.yml

Check if new beats staging artefacts are available and trigger a build if they are

Implementation of CI job to poll for new beats builds

---

.buildkite/scripts/build.ps1
Directory.Build.props

Bump version to 8.9.1
Relates to https://github.com/elastic/release-eng/issues/733

bump version to 8.9.1

---

.buildkite/pipeline.yml
.buildkite/scripts/build.ps1
Directory.Build.props

Bump version to 7.17.13
Relates to [#657](https://elasticco.atlassian.net/browse/REL-657)

bump version to 7.17.13

---

Directory.Build.props

bump ver in `Directory.Build.props`
Follow up to #173

bump projects file

---

.buildkite/scripts/build.ps1
Directory.Build.props

[Release] bump version to 7.17.14

---

.buildkite/scripts/build.ps1
Directory.Build.props

bump version to 8.9.3

---

.buildkite/scripts/build.ps1

To merge when all projects will be bumped in https://elastic.slack.com/archives/C0JFN9HJL/p1694500615643929
Related to https://github.com/elastic/release-eng/issues/763

Bump version to 8.10.1

---

.buildkite/pipeline.yml

Backport https://github.com/elastic/elastic-stack-installers/pull/186 to 8.11 branch

Transfer repo and pipeline ownership to ingest-fp (8.11)

---

.buildkite/scripts/build.ps1
Directory.Build.props

Uses a different certificate from vault 
Read the stack version from the existing properties file so we have a single place to update it

Use Alternative code signing certificate

---

.buildkite/scripts/build.ps1

Use Alternative code signing certificate #189

[Backport] [8.11] Use Alternative code signing certificate

---

.buildkite/scripts/build.ps1

Backport of Use Alternative code signing certificate #189

[Backport] [8.10] Use Alternative code signing certificate

---

.buildkite/scripts/build.ps1

Backport of : Use Alternative code signing certificate #189

[Backport] [7.17] of Use Alternative code signing certificate (#189)

---

README.md

Backport of https://github.com/elastic/elastic-stack-installers/pull/199

Add bumping doc (#199)

---

.buildkite/scripts/build.ps1
.buildkite/scripts/test.ps1
.gitignore
src/agent-qa/Invoke-Pester.ps1
src/agent-qa/Readme.md
src/agent-qa/helpers.ps1
src/agent-qa/msi.tests.ps1

Adds MSI tests to the Agent pipeline.
Currently failing due to flaky Windows uninstall in GCP

Add MSI tests for Agent Pipeline

---

catalog-info.yaml

Relates https://github.com/elastic/elastic-stack-installers/pull/229

Revert cron schedule for 8.12

---

README.md
src/build/ElastiBuild.csproj
src/installer/BeatPackageCompiler/AgentCustomAction.cs
src/installer/BeatPackageCompiler/BeatPackageCompiler.cs
src/installer/BeatPackageCompiler/Properties/launchSettings.json

Addressing cases where the user needs to customize the install folder. Example: https://github.com/elastic/elastic-stack-installers/pull/209#issuecomment-1930039248

Allow overriding INSTALLDIR

---

CODEOWNERS

Stop pinging the entire fleet platform team every time anything in here changes.

Add a more specific codeowner.

---

.buildkite/pipeline.yml

fixed to unblock `8.13` bc, needs forward porting to main
Signed-off-by: David Natachanny <David.Natachanny@elastic.co>

move snapshot dra conditional to group level

---

.buildkite/pipeline.yml
.buildkite/scripts/build.ps1

* Allow pipeline to run on 8.x branch
* Update build.ps1

Allow pipeline to run on 8.x branch (#294)

---

.buildkite/pipeline.yml
.buildkite/scripts/build.ps1

* Allow pipeline to run on 8.x branch
* Update build.ps1
(cherry picked from commit 6af1025c06802b72b73186954810897e609b9b45)

Allow pipeline to run on 8.x branch (#294) (#295)

---

.buildkite/pipeline.yml
.buildkite/scripts/dra-publish.sh

This commit adds support for VERSION_QUALIFIER to DRA.

Support prereleases
